package com.buyauto.mapper.products;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.buyauto.entity.products.TProductsImage;

public interface TProductsImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products_image
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products_image
     *
     * @mbggenerated
     */
    int insert(TProductsImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products_image
     *
     * @mbggenerated
     */
    int insertSelective(TProductsImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products_image
     *
     * @mbggenerated
     */
    TProductsImage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TProductsImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TProductsImage record);

    /**
     * 查询图片
     * @param tProductsId 
     * @return
     */
	List<TProductsImage> getTProductsPojoImage(@Param("tProductsId")Long tProductsId);

	/**
	 * 查询老图
	 * @param productsId
	 * @param thumbnail
	 * @return
	 */
	TProductsImage selectByImgEdit(@Param("productsId")Long productsId, @Param("thumbnail")int thumbnail);

	/**
	 * 查询详情图（多图）
	 * @param productsId
	 * @param recommend
	 * @return
	 */
	List<TProductsImage> selectByImgEditFigure(@Param("productsId")Long productsId, @Param("thumbnail")int thumbnail);
	/**
	 * 根据产品id获得缩略图
	 * @param tProductsId
	 * @return
	 */
	TProductsImage getTProductsImageByProductId(@Param("tProductsId")Long tProductsId);

	/**
	 * 根据产品id获得封面图
	 * @param productsId
	 * @return
	 */
	TProductsImage queryIndexTProductsPojoImageList(@Param("productsId")Long productsId);
}