package com.buyauto.mapper.products;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.buyauto.dao.products.TProductsPojo;
import com.buyauto.entity.products.TProducts;
import com.buyauto.entity.products.TProductsTemp;

public interface TProductsMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_products
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long productsId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_products
	 *
	 * @mbggenerated
	 */
	int insert(TProducts record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_products
	 *
	 * @mbggenerated
	 */
	int insertSelective(TProducts record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_products
	 *
	 * @mbggenerated
	 */
	TProducts selectByPrimaryKey(Long productsId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_products
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(TProducts record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_products
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(TProducts record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_products
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(TProducts record);

	List<TProducts> queryProductsList(@Param("title") String title, @Param("status") Integer status, @Param("startTime") Date strStartDate, @Param("endTime") Date strEndDate,
			@Param("pageStartNumber") int pageStartNumber, @Param("pageEndNumber") int pageEndNumber, @Param("productStatus") String productStatus,
			@Param("recommend") String recommend, @Param("productsId") Long productsId,@Param("operId")Long operId);

	int queryProductsCount(@Param("title") String title, @Param("status") Integer status, @Param("startTime") Date strStartDate, @Param("endTime") Date strEndDate,
			@Param("productStatus") String productStatus, @Param("recommend") String recommend, @Param("productsId") Long productsId,@Param("operId")Long operId);

	TProductsPojo showUpdateProducts(@Param("id") Long id);

	/**
	 * 展示首页热门推荐
	 * @return
	 */
	List<TProductsPojo> queryIndexRecommend();

	List<TProductsPojo> queryIndexCommodityList();

	/**
	 * 查询车库产品
	 * 
	 * @param brandId
	 * @param carType
	 * @param priceRange
	 * @param sortOrder
	 * @param title
	 * @param pageStartNumber
	 * @param pageEndNumber
	 * @return
	 */
	List<TProductsPojo> querygarageProducts(@Param("brandId") Long brandId, @Param("carType") Integer carType, @Param("priceRange") Integer priceRange,
			@Param("sortOrder") Integer sortOrder, @Param("title") String title, @Param("pageStartNumber") int pageStartNumber, @Param("pageEndNumber") int pageEndNumber);

	/**
	 * 查询车库产品数量
	 * 
	 * @param brandId
	 * @param carType
	 * @param priceRange
	 * @param title
	 * @return
	 */
	int querygarageProductsCount(@Param("brandId") Long brandId, @Param("carType") Integer carType, @Param("priceRange") Integer priceRange, @Param("title") String title);

	/**
	 * 配置商品详情
	 * 
	 * @param productsId
	 * @return
	 */
	TProductsPojo queryProductsDetailed(@Param("productsId") Long productsId);

	/**
	 * 展示商品详情
	 * 
	 * @param productsId
	 * @return
	 */
	TProductsPojo queryExhibitionTProducts(@Param("productsId") Long productsId);

	/**
	 * 查询首页展示的十条商品信息
	 * 
	 * @return
	 */
	List<TProductsPojo> queryIndexTProductsPojoList();

	/**
	 * 确定该类数据是否存在于TProducts表中
	 * 
	 * @param tProductsTemp
	 * @return
	 */
	TProducts queryExistence(@Param("tProductsTemp") TProductsTemp tProductsTemp);

	/**
	 * 锁定减少库存
	 * @param productsId
	 * @return
	 */
	Integer reduceStock(@Param("productsId")Long productsId);

	/**
	 * 释放库存
	 * @param productsId
	 * @return
	 */
	Integer releaseStock(@Param("productsId")Long productsId);

	/**
	 * 查询供应上下的所有产品Id
	 * @param id
	 * @return
	 */
	List<Long> queryListByOperId(@Param("operId")Long id);
}