package com.buyauto.mapper.products;

import java.util.List;

import com.buyauto.entity.products.TProductsTemp;

public interface TProductsTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products_temp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products_temp
     *
     * @mbggenerated
     */
    int insert(TProductsTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products_temp
     *
     * @mbggenerated
     */
    int insertSelective(TProductsTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products_temp
     *
     * @mbggenerated
     */
    TProductsTemp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products_temp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TProductsTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products_temp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TProductsTemp record);

    /**
     * 查询所有未录入的临时数据
     * @return
     */
	List<TProductsTemp> queryNotEnteredData();
}