package com.buyauto.mapper.products;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.buyauto.entity.products.TProductsCar;

public interface TProductsCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products_car
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products_car
     *
     * @mbggenerated
     */
    int insert(TProductsCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products_car
     *
     * @mbggenerated
     */
    int insertSelective(TProductsCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products_car
     *
     * @mbggenerated
     */
    TProductsCar selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TProductsCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_products_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TProductsCar record);
    /**
     * 根据产品id获得符合的车架号
     * @param productId
     * @return
     */
    List<TProductsCar> getCarNoByProId(@Param("productId") Long productId);

    /**
     * 根据车架号查询记录数
     * @param carNo
     * @return
     */
	Integer queryByCarNo(@Param("carNo")String carNo);

	/**
	 * 查询到所有可用的车架号
	 * @param productsId
	 * @return
	 */
	List<TProductsCar> queryCarNoByProductId(@Param("productsId")Long productsId);

	
	/**
	 * 更新锁定车架号
	 * @param tProductsCar2
	 * @return
	 */
	int updateByLocking(TProductsCar record);

	/**
	 * 根据车架号查询到对应的记录
	 * @param carNo
	 * @return
	 */
	TProductsCar queryCarByCarNo(@Param("carNo")String carNo);

	/**
	 * 查询对应的车架号
	 * @param id
	 * @return
	 */
	List<TProductsCar> queryCarNoByProductsId(@Param("id")Long id);
	
	/**
	 * 查询可卖产品数量(查询车架号)
	 * @param productsId
	 * @return
	 */
	int queryCarNoCount(@Param("productsId")Long productsId);
}