package com.buyauto.entity.orders;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TOrders implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -5711283104536229027L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.company_id
     *
     * @mbggenerated
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.car_id
     *
     * @mbggenerated
     */
    private Long carId;
    
    private BigDecimal carPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.configure
     *
     * @mbggenerated
     */
    private String configure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.configure_price
     *
     * @mbggenerated
     */
    private BigDecimal configurePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.take_location
     *
     * @mbggenerated
     */
    private String takeLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.deliver_time
     *
     * @mbggenerated
     */
    private String deliverTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.customer
     *
     * @mbggenerated
     */
    private String customer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.customer_tel
     *
     * @mbggenerated
     */
    private String customerTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.deposit
     *
     * @mbggenerated
     */
    private BigDecimal deposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.old_status
     *
     * @mbggenerated
     */
    private Integer oldStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.pay_status
     *
     * @mbggenerated
     */
    private Integer payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.cancel_reason
     *
     * @mbggenerated
     */
    private String cancelReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.message
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.resubmit
     *
     * @mbggenerated
     */
    private Integer resubmit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.take_way
     *
     * @mbggenerated
     */
    private Integer takeWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.complete_time
     *
     * @mbggenerated
     */
    private Date completeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.logistics_info
     *
     * @mbggenerated
     */
    private String logisticsInfo;
    
    
    private BigDecimal premiums;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.supplier_id
     *
     * @mbggenerated
     */
    private Long supplierId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.id
     *
     * @return the value of t_orders.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.id
     *
     * @param id the value for t_orders.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.user_id
     *
     * @return the value of t_orders.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.user_id
     *
     * @param userId the value for t_orders.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.company_id
     *
     * @return the value of t_orders.company_id
     *
     * @mbggenerated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.company_id
     *
     * @param companyId the value for t_orders.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.product_id
     *
     * @return the value of t_orders.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.product_id
     *
     * @param productId the value for t_orders.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.car_id
     *
     * @return the value of t_orders.car_id
     *
     * @mbggenerated
     */
    public Long getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.car_id
     *
     * @param carId the value for t_orders.car_id
     *
     * @mbggenerated
     */
    public void setCarId(Long carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.configure
     *
     * @return the value of t_orders.configure
     *
     * @mbggenerated
     */
    public String getConfigure() {
        return configure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.configure
     *
     * @param configure the value for t_orders.configure
     *
     * @mbggenerated
     */
    public void setConfigure(String configure) {
        this.configure = configure == null ? null : configure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.configure_price
     *
     * @return the value of t_orders.configure_price
     *
     * @mbggenerated
     */
    public BigDecimal getConfigurePrice() {
        return configurePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.configure_price
     *
     * @param configurePrice the value for t_orders.configure_price
     *
     * @mbggenerated
     */
    public void setConfigurePrice(BigDecimal configurePrice) {
        this.configurePrice = configurePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.amount
     *
     * @return the value of t_orders.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.amount
     *
     * @param amount the value for t_orders.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.take_location
     *
     * @return the value of t_orders.take_location
     *
     * @mbggenerated
     */
    public String getTakeLocation() {
        return takeLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.take_location
     *
     * @param takeLocation the value for t_orders.take_location
     *
     * @mbggenerated
     */
    public void setTakeLocation(String takeLocation) {
        this.takeLocation = takeLocation == null ? null : takeLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.deliver_time
     *
     * @return the value of t_orders.deliver_time
     *
     * @mbggenerated
     */
    public String getDeliverTime() {
        return deliverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.deliver_time
     *
     * @param deliverTime the value for t_orders.deliver_time
     *
     * @mbggenerated
     */
    public void setDeliverTime(String deliverTime) {
        this.deliverTime = deliverTime == null ? null : deliverTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.customer
     *
     * @return the value of t_orders.customer
     *
     * @mbggenerated
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.customer
     *
     * @param customer the value for t_orders.customer
     *
     * @mbggenerated
     */
    public void setCustomer(String customer) {
        this.customer = customer == null ? null : customer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.customer_tel
     *
     * @return the value of t_orders.customer_tel
     *
     * @mbggenerated
     */
    public String getCustomerTel() {
        return customerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.customer_tel
     *
     * @param customerTel the value for t_orders.customer_tel
     *
     * @mbggenerated
     */
    public void setCustomerTel(String customerTel) {
        this.customerTel = customerTel == null ? null : customerTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.deposit
     *
     * @return the value of t_orders.deposit
     *
     * @mbggenerated
     */
    public BigDecimal getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.deposit
     *
     * @param deposit the value for t_orders.deposit
     *
     * @mbggenerated
     */
    public void setDeposit(BigDecimal deposit) {
        this.deposit = deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.status
     *
     * @return the value of t_orders.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.status
     *
     * @param status the value for t_orders.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.old_status
     *
     * @return the value of t_orders.old_status
     *
     * @mbggenerated
     */
    public Integer getOldStatus() {
        return oldStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.old_status
     *
     * @param oldStatus the value for t_orders.old_status
     *
     * @mbggenerated
     */
    public void setOldStatus(Integer oldStatus) {
        this.oldStatus = oldStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.pay_status
     *
     * @return the value of t_orders.pay_status
     *
     * @mbggenerated
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.pay_status
     *
     * @param payStatus the value for t_orders.pay_status
     *
     * @mbggenerated
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.cancel_reason
     *
     * @return the value of t_orders.cancel_reason
     *
     * @mbggenerated
     */
    public String getCancelReason() {
        return cancelReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.cancel_reason
     *
     * @param cancelReason the value for t_orders.cancel_reason
     *
     * @mbggenerated
     */
    public void setCancelReason(String cancelReason) {
        this.cancelReason = cancelReason == null ? null : cancelReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.message
     *
     * @return the value of t_orders.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.message
     *
     * @param message the value for t_orders.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.create_date
     *
     * @return the value of t_orders.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.create_date
     *
     * @param createDate the value for t_orders.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.update_date
     *
     * @return the value of t_orders.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.update_date
     *
     * @param updateDate the value for t_orders.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.resubmit
     *
     * @return the value of t_orders.resubmit
     *
     * @mbggenerated
     */
    public Integer getResubmit() {
        return resubmit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.resubmit
     *
     * @param resubmit the value for t_orders.resubmit
     *
     * @mbggenerated
     */
    public void setResubmit(Integer resubmit) {
        this.resubmit = resubmit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.count
     *
     * @return the value of t_orders.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.count
     *
     * @param count the value for t_orders.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.version
     *
     * @return the value of t_orders.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.version
     *
     * @param version the value for t_orders.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.take_way
     *
     * @return the value of t_orders.take_way
     *
     * @mbggenerated
     */
    public Integer getTakeWay() {
        return takeWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.take_way
     *
     * @param takeWay the value for t_orders.take_way
     *
     * @mbggenerated
     */
    public void setTakeWay(Integer takeWay) {
        this.takeWay = takeWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.complete_time
     *
     * @return the value of t_orders.complete_time
     *
     * @mbggenerated
     */
    public Date getCompleteTime() {
        return completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.complete_time
     *
     * @param completeTime the value for t_orders.complete_time
     *
     * @mbggenerated
     */
    public void setCompleteTime(Date completeTime) {
        this.completeTime = completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.logistics_info
     *
     * @return the value of t_orders.logistics_info
     *
     * @mbggenerated
     */
    public String getLogisticsInfo() {
        return logisticsInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.logistics_info
     *
     * @param logisticsInfo the value for t_orders.logistics_info
     *
     * @mbggenerated
     */
    public void setLogisticsInfo(String logisticsInfo) {
        this.logisticsInfo = logisticsInfo == null ? null : logisticsInfo.trim();
    }

	public BigDecimal getPremiums() {
		return premiums;
	}

	public void setPremiums(BigDecimal premiums) {
		this.premiums = premiums;
	}

	public BigDecimal getCarPrice() {
		return carPrice;
	}

	public void setCarPrice(BigDecimal carPrice) {
		this.carPrice = carPrice;
	}

	public Long getSupplierId() {
		return supplierId;
	}

	public void setSupplierId(Long supplierId) {
		this.supplierId = supplierId;
	}
    
	
	
	
}