package com.buyauto.mapper.sys;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.buyauto.entity.sys.SysConfig;

public interface SysConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated
     */
    int insert(SysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated
     */
    int insertSelective(SysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated
     */
    SysConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysConfig record);

	int queryaddressListCount(@Param("scvalue")String scvalue, @Param("state")Integer state,@Param("startTime")Date startTime,
			@Param("endTime")Date endTime, @Param("group")String extractAddress);

	List<SysConfig> queryaddressList(@Param("scvalue")String scvalue, @Param("state")Integer state,
			@Param("pageStartNumber")int pageStartNumber, @Param("pageEndNumber")int pageEndNumber,@Param("startTime")Date startTime,
			@Param("endTime")Date endTime, @Param("group")String extractAddress);

	List<SysConfig> queryPackList();

	List<SysConfig> querySysConfigtractList(@Param("carBrand")String carBrand);

	/**
	 * 查询是否有重名地址
	 * @param scValue
	 * @return
	 */
	Integer querySame(@Param("scValue")String scValue);

	/**
	 * 查询可选配置
	 * @param optionalConfig
	 * @return
	 */
	List<SysConfig> queryOptionalList(@Param("group")String optionalConfig);

	/**
	 * 查询是否存在temp表中对应的品牌
	 * @param brand
	 * @param carBrand 
	 * @return
	 */
	SysConfig queryTempBrand(@Param("brand")String brand, @Param("carBrand")String carBrand);

	
	/**
	 * 根据groupName和State查询
	 * @param upgradeConfig
	 * @param enable
	 * @return
	 */
	SysConfig queryByGroupNameAndState(@Param("groupName")String upgradeConfig, @Param("state")int enable);

	/**
	 * @param pageSize 
	 * @param pageNumber  
	* @Title: queryCommissionConfig 
	* @Description: 查询佣金配置
	* @return TOrdersCommission    返回类型 
	* @throws 
	*/
	List<SysConfig> queryCommissionConfig(@Param("groupName")String groupName,@Param("pageStartNumber")int pageStartNumber, @Param("pageEndNumber")int pageEndNumber);

	int queryCommissionConfigCount(@Param("groupName")String groupName);

	void updateStatusById(@Param("id")Long id, @Param("state")Integer result);

	void updateValueByKey(@Param("scValue")String scValue,@Param("scKey") String key);

	SysConfig queryByGroupNameAndKey(@Param("groupName")String groupName,@Param("scKey") String key);

	SysConfig queryByGroupNameAndStateAndRemark(@Param("groupName")String upgradeDowngrade,@Param("state") int enable,@Param("remark") String personalUpgrade);
}