package com.buyauto.mapper.sys;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.buyauto.entity.sys.SysRuleUser;

public interface SysRuleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_user
     *
     * @mbggenerated
     */
    int insert(SysRuleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_user
     *
     * @mbggenerated
     */
    int insertSelective(SysRuleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_user
     *
     * @mbggenerated
     */
    SysRuleUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRuleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRuleUser record);
    /**
	 * 
	 * @Title: queryUserByName
	 * @Description: 通过管理员用户名查询管理员
	 * @param @param name
	 * @param @return 设定文件
	 * @return SysRuleUser 返回类型
	 * @throws
	 */
	SysRuleUser queryUserByName(@Param("userName") String name);
	
	List<SysRuleUser> queryRuleUser(@Param("isTrue") Integer isTrue,
	    		@Param("startNumber") int startNumber,@Param("endNumber") int endNumber);
	    
    int queryRuleUserCount(@Param("isTrue") int isTrue);
    
    /**
     * 根据ID查姓名
     */
    String getNameById(@Param("id") Long id);
    
    SysRuleUser getUserInfo(@Param("id") Long id);
}