package com.buyauto.mapper.sys;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.buyauto.entity.sys.SysRuleOperation;

public interface SysRuleOperationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_operation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_operation
     *
     * @mbggenerated
     */
    int insert(SysRuleOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_operation
     *
     * @mbggenerated
     */
    int insertSelective(SysRuleOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_operation
     *
     * @mbggenerated
     */
    SysRuleOperation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_operation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRuleOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_operation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRuleOperation record);
    
    
    List<SysRuleOperation> queryOperation(@Param("startNumber") int startNumber,
			@Param("endNumber") int endNumber);
    
    int queryOperationCount();
    
	List<SysRuleOperation> selectAllOperationsByModule(@Param("mId")Long mid);
}