package com.buyauto.mapper.sys;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.buyauto.entity.sys.SysRuleMoudle;

public interface SysRuleMoudleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_moudle
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_moudle
     *
     * @mbggenerated
     */
    int insert(SysRuleMoudle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_moudle
     *
     * @mbggenerated
     */
    int insertSelective(SysRuleMoudle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_moudle
     *
     * @mbggenerated
     */
    SysRuleMoudle selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_moudle
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRuleMoudle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_moudle
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRuleMoudle record);
    /**
	 * 
	 * @Title: queryListByFather
	 * @Description: 根据父类查询所有数据
	 * @param @param fatherId
	 * @param @param isEnable
	 * @param @return 设定文件
	 * @return List<SysRuleMoudle> 返回类型
	 * @throws
	 */
	List<SysRuleMoudle> queryListByFather(@Param("fatherId") Long fatherId);
}