package com.buyauto.mapper.sys;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.buyauto.entity.sys.SysRuleUserrole;

public interface SysRuleUserroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_userrole
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_userrole
     *
     * @mbggenerated
     */
    int insert(SysRuleUserrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_userrole
     *
     * @mbggenerated
     */
    int insertSelective(SysRuleUserrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_userrole
     *
     * @mbggenerated
     */
    SysRuleUserrole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_userrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRuleUserrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_userrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRuleUserrole record);
    
    List<Long> selectByUid(@Param("userId") Long id);
    
    int deleteByUserId(Long userId);
    
    SysRuleUserrole selectByUserId(Long userId);
    
    Long getRoleIdByRoleName();
    
    List<Long> getCheckerId(@Param("roleId") Long roleId);
    
}