package com.buyauto.mapper.sys;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.buyauto.entity.sys.SysRulePrivilege;

public interface SysRulePrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_privilege
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_privilege
     *
     * @mbggenerated
     */
    int insert(SysRulePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_privilege
     *
     * @mbggenerated
     */
    int insertSelective(SysRulePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_privilege
     *
     * @mbggenerated
     */
    SysRulePrivilege selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_privilege
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRulePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_privilege
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRulePrivilege record);
    
    /**
     * 查询用户权限列表
     * */
    List<Long> findByUserId(Long userId);
    
    /**
     * 查询用户角色权限列表
     * */
    List<Long> findRuleByRoleId(Long roleId);
    
    List<SysRulePrivilege> selectPrivilege(@Param("rmaster")int master, @Param("rprivilegeId")Long privilegeId, @Param("rruleType")int ruleType);
    
    int deletePrivilegeWithRuleId(@Param("privilegeId")Long privilegeId);
}