package com.buyauto.mapper.sys;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.buyauto.entity.sys.SysScheduled;

public interface SysScheduledMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduled
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduled
     *
     * @mbggenerated
     */
    int insert(SysScheduled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduled
     *
     * @mbggenerated
     */
    int insertSelective(SysScheduled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduled
     *
     * @mbggenerated
     */
    SysScheduled selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduled
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysScheduled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduled
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysScheduled record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_scheduled
	 *
	 * @mbggenerated Wed Dec 17 11:32:34 CST 2014
	 */
	List<SysScheduled> selectAll();

	/**
	 * 根据job名称和对账日查询当前job
	 * 
	 * @param jobName
	 * @param reconDay
	 * @return
	 */
	SysScheduled selectJobInfo(@Param("jobBizName") String jobBizName, @Param("reconDay") String reconDay);

	/**
	 * 更新job状态
	 * 
	 * @param jobName
	 *            job名称
	 * @param reconDay
	 *            对账日
	 * @param oldStatus
	 *            job执行之前的状态
	 * @param status
	 *            当前新状态
	 * @param version
	 *            版本控制
	 * @return
	 */
	int updateJobStatus(@Param("jobBizName") String jobBizName, @Param("reconDay") String reconDay, @Param("oldStatus") int oldStatus,
			@Param("status") int status, @Param("version") int version);

	/**
	 * 更新执行时间
	 * 
	 * @param id
	 * @param endDate
	 * @param interval
	 * @return
	 */
	int updateJobExecuteTime(@Param("id") long id, @Param("endDate") Date endDate, @Param("interval") long interval, @Param("version") int version);

	/**
	 * 更新job开始时间
	 * 
	 * @param id
	 * @param startDate
	 * @return
	 */
	int updateJobStartTime(@Param("id") long id, @Param("startDate") Date startDate, @Param("version") int version);
}