package com.buyauto.mapper.log;

import com.buyauto.entity.log.LogAdminAction;


public interface LogAdminActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_admin_action
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_admin_action
     *
     * @mbggenerated
     */
    int insert(LogAdminAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_admin_action
     *
     * @mbggenerated
     */
    int insertSelective(LogAdminAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_admin_action
     *
     * @mbggenerated
     */
    LogAdminAction selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_admin_action
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LogAdminAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_admin_action
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LogAdminAction record);
}