package com.buyauto.mapper.log;

import com.buyauto.entity.log.LogErrorAction;


public interface LogErrorActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_error_action
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_error_action
     *
     * @mbggenerated
     */
    int insert(LogErrorAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_error_action
     *
     * @mbggenerated
     */
    int insertSelective(LogErrorAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_error_action
     *
     * @mbggenerated
     */
    LogErrorAction selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_error_action
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LogErrorAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_error_action
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(LogErrorAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_error_action
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LogErrorAction record);
}