package com.buyauto.mapper.log;

import org.apache.ibatis.annotations.Param;

import com.buyauto.entity.log.LogLogin;

public interface LogLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_login
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_login
     *
     * @mbggenerated
     */
    int insert(LogLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_login
     *
     * @mbggenerated
     */
    int insertSelective(LogLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_login
     *
     * @mbggenerated
     */
    LogLogin selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_login
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LogLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_login
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LogLogin record);

    /**
     * 根据登录名进行查找登录次数
     * @param account
     * @return
     */
	Integer findCountByAccount(@Param("account") String account);
}