package com.buyauto.dao.products;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.Map;

import com.buyauto.entity.products.TProductsImage;
import com.buyauto.entity.sys.SysConfig;

public class TProductsPojo implements Serializable {

	/**
	 * 
	 */
	public static final long serialVersionUID = 3247350606771159020L;

	public String scValue;/*品牌名称*/
	public Long productsId;/*产品ID*/
	public Long brandId;/*品牌ID*/
	public Integer carType;//0轿车1SUV2MPV3皮卡4卡车5跑车
	public Integer priceRange;//0:50以下,1:100以下,2:150以下,3:150以上
	public Integer position;//0港口现车1预定车2在途车
	public Integer selfSupport;//是否自营:0否1是
	
	public BigDecimal personal;//个人客户加价
	public BigDecimal sales;//个人销售加价
	public BigDecimal distributor;//经销商加价
	public String title;//标题
	public List<TProductsImage> tProductsImage;// 图片集合
	public String imgfilePath; /*图片前缀*/
	public String filePath;// 图片
	public String gearbox;//变速箱
	public Integer deposit;//定金支付比例
	public List<SysConfig> extract;// 提车地址
	public String extractPerson;// 提车人
	public Long extractPhone;// 提车人电话
	public SysConfig sysConfigAddress;// 订单确认页提车地址
	public String extractDate;// 提车时间
	public String distribution;// 配送地址
	public String deliveryMode;// 配送方式
	public String doors;//门数
	public String seats;//座位数
	public String remarks;//备注
	public String carStandards;//车辆标准
	public String carModel;//车辆型号
	public String outColor;//车体外观颜色
	public String inColor;//车身内部颜色
	public String country;//原产地
	public String power;//动力
	public String engine;//发动机
	public Date factoryDate;//出厂日期
	public BigDecimal chinaPrice;//国内指导价
	public String basicConfigure;//基础配置
	public String mustConfigure;//必选配置
	public String optionalConfigure;//可选配置(json)
	public BigDecimal carPrice;//裸车价格(麦卡价格)
	public BigDecimal mustConfigurePrice;//必选件总价
	public Integer status;//0草稿箱，1新建，2上架，3回收站，4审核通过，5审核不通过
	public Integer recommend;//0不推荐，1推荐
	public Integer stock;//库存
	public Long operId;//输入人ID
	public String content;//富文本
	
	List<Map<String,Object>> optionalConfigureList;//可选配置集合(提供APP解析)
	
	public Date updateDate;
	public Integer version;
	public Date createDate;
	
	public String indexImageH;
	public String shrinkImageH;
	public String detailedImageH;
	
	public int carNoCount;
	public Integer insuranceType;//保险方式
	public BigDecimal insuranceAmount;//保险金额
	public String insuranceName;//保险名称
	
	public BigDecimal getInsuranceAmount() {
		return insuranceAmount;
	}

	public void setInsuranceAmount(BigDecimal insuranceAmount) {
		this.insuranceAmount = insuranceAmount;
	}

	public Integer getInsuranceType() {
		return insuranceType;
	}

	public void setInsuranceType(Integer insuranceType) {
		this.insuranceType = insuranceType;
	}

	

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.products_id
	 *
	 * @return the value of t_products.products_id
	 *
	 * @mbggenerated
	 */
	public Long getProductsId() {
		return productsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.products_id
	 *
	 * @param productsId
	 *            the value for t_products.products_id
	 *
	 * @mbggenerated
	 */
	public void setProductsId(Long productsId) {
		this.productsId = productsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.brand_id
	 *
	 * @return the value of t_products.brand_id
	 *
	 * @mbggenerated
	 */
	public Long getBrandId() {
		return brandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.brand_id
	 *
	 * @param brandId
	 *            the value for t_products.brand_id
	 *
	 * @mbggenerated
	 */
	public void setBrandId(Long brandId) {
		this.brandId = brandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.car_type
	 *
	 * @return the value of t_products.car_type
	 *
	 * @mbggenerated
	 */
	public Integer getCarType() {
		return carType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.car_type
	 *
	 * @param carType
	 *            the value for t_products.car_type
	 *
	 * @mbggenerated
	 */
	public void setCarType(Integer carType) {
		this.carType = carType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.price_range
	 *
	 * @return the value of t_products.price_range
	 *
	 * @mbggenerated
	 */
	public Integer getPriceRange() {
		return priceRange;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.price_range
	 *
	 * @param priceRange
	 *            the value for t_products.price_range
	 *
	 * @mbggenerated
	 */
	public void setPriceRange(Integer priceRange) {
		this.priceRange = priceRange;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.position
	 *
	 * @return the value of t_products.position
	 *
	 * @mbggenerated
	 */
	public Integer getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.position
	 *
	 * @param position
	 *            the value for t_products.position
	 *
	 * @mbggenerated
	 */
	public void setPosition(Integer position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.title
	 *
	 * @return the value of t_products.title
	 *
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.title
	 *
	 * @param title
	 *            the value for t_products.title
	 *
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.car_model
	 *
	 * @return the value of t_products.car_model
	 *
	 * @mbggenerated
	 */
	public String getCarModel() {
		return carModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.car_model
	 *
	 * @param carModel
	 *            the value for t_products.car_model
	 *
	 * @mbggenerated
	 */
	public void setCarModel(String carModel) {
		this.carModel = carModel == null ? null : carModel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.out_color
	 *
	 * @return the value of t_products.out_color
	 *
	 * @mbggenerated
	 */
	public String getOutColor() {
		return outColor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.out_color
	 *
	 * @param outColor
	 *            the value for t_products.out_color
	 *
	 * @mbggenerated
	 */
	public void setOutColor(String outColor) {
		this.outColor = outColor == null ? null : outColor.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.in_color
	 *
	 * @return the value of t_products.in_color
	 *
	 * @mbggenerated
	 */
	public String getInColor() {
		return inColor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.in_color
	 *
	 * @param inColor
	 *            the value for t_products.in_color
	 *
	 * @mbggenerated
	 */
	public void setInColor(String inColor) {
		this.inColor = inColor == null ? null : inColor.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.country
	 *
	 * @return the value of t_products.country
	 *
	 * @mbggenerated
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.country
	 *
	 * @param country
	 *            the value for t_products.country
	 *
	 * @mbggenerated
	 */
	public void setCountry(String country) {
		this.country = country == null ? null : country.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.power
	 *
	 * @return the value of t_products.power
	 *
	 * @mbggenerated
	 */
	public String getPower() {
		return power;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.power
	 *
	 * @param power
	 *            the value for t_products.power
	 *
	 * @mbggenerated
	 */
	public void setPower(String power) {
		this.power = power == null ? null : power.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.engine
	 *
	 * @return the value of t_products.engine
	 *
	 * @mbggenerated
	 */
	public String getEngine() {
		return engine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.engine
	 *
	 * @param engine
	 *            the value for t_products.engine
	 *
	 * @mbggenerated
	 */
	public void setEngine(String engine) {
		this.engine = engine == null ? null : engine.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.factory_date
	 *
	 * @return the value of t_products.factory_date
	 *
	 * @mbggenerated
	 */
	public Date getFactoryDate() {
		return factoryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.factory_date
	 *
	 * @param factoryDate
	 *            the value for t_products.factory_date
	 *
	 * @mbggenerated
	 */
	public void setFactoryDate(Date factoryDate) {
		this.factoryDate = factoryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.china_price
	 *
	 * @return the value of t_products.china_price
	 *
	 * @mbggenerated
	 */
	public BigDecimal getChinaPrice() {
		return chinaPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.china_price
	 *
	 * @param chinaPrice
	 *            the value for t_products.china_price
	 *
	 * @mbggenerated
	 */
	public void setChinaPrice(BigDecimal chinaPrice) {
		this.chinaPrice = chinaPrice;
	}

	public String getBasicConfigure() {
		return basicConfigure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.basic_configure
	 *
	 * @param basicConfigure
	 *            the value for t_products.basic_configure
	 *
	 * @mbggenerated
	 */
	public void setBasicConfigure(String basicConfigure) {
		this.basicConfigure = basicConfigure == null ? null : basicConfigure
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.must_configure
	 *
	 * @return the value of t_products.must_configure
	 *
	 * @mbggenerated
	 */
	public String getMustConfigure() {
		return mustConfigure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.must_configure
	 *
	 * @param mustConfigure
	 *            the value for t_products.must_configure
	 *
	 * @mbggenerated
	 */
	public void setMustConfigure(String mustConfigure) {
		this.mustConfigure = mustConfigure == null ? null : mustConfigure
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.optional_configure
	 *
	 * @return the value of t_products.optional_configure
	 *
	 * @mbggenerated
	 */
	public String getOptionalConfigure() {
		return optionalConfigure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.optional_configure
	 *
	 * @param optionalConfigure
	 *            the value for t_products.optional_configure
	 *
	 * @mbggenerated
	 */
	public void setOptionalConfigure(String optionalConfigure) {
		this.optionalConfigure = optionalConfigure == null ? null
				: optionalConfigure.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.car_price
	 *
	 * @return the value of t_products.car_price
	 *
	 * @mbggenerated
	 */
	public BigDecimal getCarPrice() {
		return carPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.car_price
	 *
	 * @param carPrice
	 *            the value for t_products.car_price
	 *
	 * @mbggenerated
	 */
	public void setCarPrice(BigDecimal carPrice) {
		this.carPrice = carPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.must_configure_price
	 *
	 * @return the value of t_products.must_configure_price
	 *
	 * @mbggenerated
	 */
	public BigDecimal getMustConfigurePrice() {
		return mustConfigurePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.must_configure_price
	 *
	 * @param mustConfigurePrice
	 *            the value for t_products.must_configure_price
	 *
	 * @mbggenerated
	 */
	public void setMustConfigurePrice(BigDecimal mustConfigurePrice) {
		this.mustConfigurePrice = mustConfigurePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.status
	 *
	 * @return the value of t_products.status
	 *
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.status
	 *
	 * @param status
	 *            the value for t_products.status
	 *
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.recommend
	 *
	 * @return the value of t_products.recommend
	 *
	 * @mbggenerated
	 */
	public Integer getRecommend() {
		return recommend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.recommend
	 *
	 * @param recommend
	 *            the value for t_products.recommend
	 *
	 * @mbggenerated
	 */
	public void setRecommend(Integer recommend) {
		this.recommend = recommend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.stock
	 *
	 * @return the value of t_products.stock
	 *
	 * @mbggenerated
	 */
	public Integer getStock() {
		return stock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.stock
	 *
	 * @param stock
	 *            the value for t_products.stock
	 *
	 * @mbggenerated
	 */
	public void setStock(Integer stock) {
		this.stock = stock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.create_date
	 *
	 * @return the value of t_products.create_date
	 *
	 * @mbggenerated
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.create_date
	 *
	 * @param createDate
	 *            the value for t_products.create_date
	 *
	 * @mbggenerated
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.oper_id
	 *
	 * @return the value of t_products.oper_id
	 *
	 * @mbggenerated
	 */
	public Long getOperId() {
		return operId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.oper_id
	 *
	 * @param operId
	 *            the value for t_products.oper_id
	 *
	 * @mbggenerated
	 */
	public void setOperId(Long operId) {
		this.operId = operId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.update_date
	 *
	 * @return the value of t_products.update_date
	 *
	 * @mbggenerated
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.update_date
	 *
	 * @param updateDate
	 *            the value for t_products.update_date
	 *
	 * @mbggenerated
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.version
	 *
	 * @return the value of t_products.version
	 *
	 * @mbggenerated
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.version
	 *
	 * @param version
	 *            the value for t_products.version
	 *
	 * @mbggenerated
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_products.content
	 *
	 * @return the value of t_products.content
	 *
	 * @mbggenerated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_products.content
	 *
	 * @param content
	 *            the value for t_products.content
	 *
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	public String getScValue() {
		return scValue;
	}

	public void setScValue(String scValue) {
		this.scValue = scValue;
	}

	public String getIndexImageH() {
		return indexImageH;
	}

	public void setIndexImageH(String indexImageH) {
		this.indexImageH = indexImageH;
	}

	public String getShrinkImageH() {
		return shrinkImageH;
	}

	public void setShrinkImageH(String shrinkImageH) {
		this.shrinkImageH = shrinkImageH;
	}

	public String getDetailedImageH() {
		return detailedImageH;
	}

	public void setDetailedImageH(String detailedImageH) {
		this.detailedImageH = detailedImageH;
	}

	public List<TProductsImage> gettProductsImage() {
		return tProductsImage;
	}

	public void settProductsImage(List<TProductsImage> tProductsImage) {
		this.tProductsImage = tProductsImage;
	}

	public String getImgfilePath() {
		return imgfilePath;
	}

	public void setImgfilePath(String imgfilePath) {
		this.imgfilePath = imgfilePath;
	}

	public String getFilePath() {
		return filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public String getGearbox() {
		return gearbox;
	}

	public void setGearbox(String gearbox) {
		this.gearbox = gearbox;
	}

	public Integer getDeposit() {
		return deposit;
	}

	public void setDeposit(Integer deposit) {
		this.deposit = deposit;
	}

	public List<SysConfig> getExtract() {
		return extract;
	}

	public void setExtract(List<SysConfig> extract) {
		this.extract = extract;
	}

	public String getExtractPerson() {
		return extractPerson;
	}

	public void setExtractPerson(String extractPerson) {
		this.extractPerson = extractPerson;
	}

	public Long getExtractPhone() {
		return extractPhone;
	}

	public void setExtractPhone(Long extractPhone) {
		this.extractPhone = extractPhone;
	}

	public SysConfig getSysConfigAddress() {
		return sysConfigAddress;
	}

	public void setSysConfigAddress(SysConfig sysConfigAddress) {
		this.sysConfigAddress = sysConfigAddress;
	}

	public String getExtractDate() {
		return extractDate;
	}

	public void setExtractDate(String extractDate) {
		this.extractDate = extractDate;
	}

	public String getDistribution() {
		return distribution;
	}

	public void setDistribution(String distribution) {
		this.distribution = distribution;
	}

	public String getDeliveryMode() {
		return deliveryMode;
	}

	public void setDeliveryMode(String deliveryMode) {
		this.deliveryMode = deliveryMode;
	}

	public String getDoors() {
		return doors;
	}

	public void setDoors(String doors) {
		this.doors = doors;
	}

	public String getSeats() {
		return seats;
	}

	public void setSeats(String seats) {
		this.seats = seats;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getCarStandards() {
		return carStandards;
	}

	public void setCarStandards(String carStandards) {
		this.carStandards = carStandards;
	}

	public int getCarNoCount() {
		return carNoCount;
	}

	public void setCarNoCount(int carNoCount) {
		this.carNoCount = carNoCount;
	}

	public Integer getSelfSupport() {
		return selfSupport;
	}

	public void setSelfSupport(Integer selfSupport) {
		this.selfSupport = selfSupport;
	}

	public BigDecimal getPersonal() {
		return personal;
	}

	public void setPersonal(BigDecimal personal) {
		this.personal = personal;
	}

	public BigDecimal getSales() {
		return sales;
	}

	public void setSales(BigDecimal sales) {
		this.sales = sales;
	}

	public BigDecimal getDistributor() {
		return distributor;
	}

	public void setDistributor(BigDecimal distributor) {
		this.distributor = distributor;
	}

	@Override
	public String toString() {
		return "TProductsPojo [scValue=" + scValue + ", productsId="
				+ productsId + ", brandId=" + brandId + ", carType=" + carType
				+ ", priceRange=" + priceRange + ", position=" + position
				+ ", selfSupport=" + selfSupport + ", personal=" + personal
				+ ", sales=" + sales + ", distributor=" + distributor
				+ ", title=" + title + ", indexImageH=" + indexImageH
				+ ", shrinkImageH=" + shrinkImageH + ", detailedImageH="
				+ detailedImageH + ", tProductsImage=" + tProductsImage
				+ ", imgfilePath=" + imgfilePath + ", filePath=" + filePath
				+ ", gearbox=" + gearbox + ", deposit=" + deposit
				+ ", extract=" + extract + ", extractPerson=" + extractPerson
				+ ", extractPhone=" + extractPhone + ", sysConfigAddress="
				+ sysConfigAddress + ", extractDate=" + extractDate
				+ ", distribution=" + distribution + ", deliveryMode="
				+ deliveryMode + ", doors=" + doors + ", seats=" + seats
				+ ", remarks=" + remarks + ", carStandards=" + carStandards
				+ ", carNoCount=" + carNoCount + ", carModel=" + carModel
				+ ", outColor=" + outColor + ", inColor=" + inColor
				+ ", country=" + country + ", power=" + power + ", engine="
				+ engine + ", factoryDate=" + factoryDate + ", chinaPrice="
				+ chinaPrice + ", basicConfigure=" + basicConfigure
				+ ", mustConfigure=" + mustConfigure + ", optionalConfigure="
				+ optionalConfigure + ", carPrice=" + carPrice
				+ ", mustConfigurePrice=" + mustConfigurePrice + ", status="
				+ status + ", recommend=" + recommend + ", stock=" + stock
				+ ", createDate=" + createDate + ", operId=" + operId
				+ ", updateDate=" + updateDate + ", version=" + version
				+ ", content=" + content + "]";
	}

	public String getInsuranceName() {
		return insuranceName;
	}

	public void setInsuranceName(String insuranceName) {
		this.insuranceName = insuranceName;
	}

	public List<Map<String, Object>> getOptionalConfigureList() {
		return optionalConfigureList;
	}

	public void setOptionalConfigureList(List<Map<String, Object>> optionalConfigureList) {
		this.optionalConfigureList = optionalConfigureList;
	}

}