package com.buyauto.mapper.cms;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.buyauto.dao.cms.CmsBannerPojo;
import com.buyauto.entity.cms.CmsBanner;

public interface CmsBannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_banner
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_banner
     *
     * @mbggenerated
     */
    int insert(CmsBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_banner
     *
     * @mbggenerated
     */
    int insertSelective(CmsBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_banner
     *
     * @mbggenerated
     */
    CmsBanner selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_banner
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CmsBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_banner
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmsBanner record);


	//查
	List<CmsBannerPojo> queryBanner(@Param("startNumber") int startNumber,@Param("endNumber") int endNumber,@Param("startTime") Date strStartDates,@Param("endTime")  Date strEndDates, @Param("state") Integer state,@Param("title")  String title);
	//总条数
	int queryBannerCount(@Param("startTime") Date strStartDates,@Param("endTime")  Date strEndDates, @Param("state") Integer state,@Param("title")  String title);
	//根据id查banner
	CmsBannerPojo getByid(Long id);
	//根据title查banner
	CmsBanner getByTitle(@Param("title") String title);
	/**
	 * 查询首页展示的banner
	 * @return
	 */
	List<CmsBannerPojo> queryIndexBannerList();

	/**
	 * 查询banner上线条数
	 */
	Integer fingBannerByOnline();
}