package com.buyauto.mapper.orders;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.buyauto.dao.user.TOrderFinanceDao;
import com.buyauto.entity.orders.TOrderFinance;

public interface TOrderFinanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_finance
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_finance
     *
     * @mbggenerated
     */
    int insert(TOrderFinance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_finance
     *
     * @mbggenerated
     */
    int insertSelective(TOrderFinance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_finance
     *
     * @mbggenerated
     */
    TOrderFinance selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_finance
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TOrderFinance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_finance
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TOrderFinance record);

	List<TOrderFinanceDao> queryFinanceAudit(@Param("pageStartNumber")int pageStartNumber,@Param("pageEndNumber") int pageEndNumber,@Param("status") String status,@Param("name") String name,
			@Param("phone")String phone,@Param("startTime") Date strStartDates,@Param("endTime") Date strEndDates);

	int queryFinanceAuditCount(@Param("startTime")Date strStartDates,@Param("endTime") Date strEndDates,@Param("status") String status,@Param("name") String name,@Param("phone") String phone);

	TOrderFinance selectByOrderId(@Param("orderId")Long orderId);
}