package com.buyauto.mapper.orders;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.buyauto.entity.orders.TOrdersFiles;

public interface TOrdersFilesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders_files
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders_files
     *
     * @mbggenerated
     */
    int insert(TOrdersFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders_files
     *
     * @mbggenerated
     */
    int insertSelective(TOrdersFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders_files
     *
     * @mbggenerated
     */
    TOrdersFiles selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders_files
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TOrdersFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders_files
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TOrdersFiles record);
    
    /**
     * 根据订单id查找钱款凭证(多图)
     * @param orderId
     * @return
     */
    List<TOrdersFiles> getOrdersFilesByOrderId(@Param("orderId") Long orderId, @Param("type") Integer type);
    /**
     * 产询付款
     * @param orderId
     * @param type
     * @return
     */
    List<TOrdersFiles> getOrdersFilesPaied(@Param("orderId") Long orderId);
}