package com.buyauto.mapper.orders;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.buyauto.dao.orders.TUsersCommissionDao;
import com.buyauto.entity.orders.TOrdersCommission;

public interface TOrdersCommissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders_commission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders_commission
     *
     * @mbggenerated
     */
    int insert(TOrdersCommission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders_commission
     *
     * @mbggenerated
     */
    int insertSelective(TOrdersCommission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders_commission
     *
     * @mbggenerated
     */
    TOrdersCommission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders_commission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TOrdersCommission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orders_commission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TOrdersCommission record);

	List<TUsersCommissionDao> getUsersCommissionList(@Param("uId")Long uId,@Param("pageStartNumber") int pageStartNumber,
			@Param("pageEndNumber") int pageEndNumber);

	Integer getUsersCommissionByCount(@Param("uId")Long uId);
}