package com.buyauto.entity.sys;

import java.util.Date;

public class SysRuleMoudle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_moudle.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_moudle.top_num
     *
     * @mbggenerated
     */
    private Long topNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_moudle.moudle_father
     *
     * @mbggenerated
     */
    private Long moudleFather;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_moudle.moudle_name
     *
     * @mbggenerated
     */
    private String moudleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_moudle.moudle_desc
     *
     * @mbggenerated
     */
    private String moudleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_moudle.create_user
     *
     * @mbggenerated
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_moudle.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_moudle.update_user
     *
     * @mbggenerated
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_moudle.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_moudle.is_enable
     *
     * @mbggenerated
     */
    private Short isEnable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_moudle.id
     *
     * @return the value of sys_rule_moudle.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_moudle.id
     *
     * @param id the value for sys_rule_moudle.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_moudle.top_num
     *
     * @return the value of sys_rule_moudle.top_num
     *
     * @mbggenerated
     */
    public Long getTopNum() {
        return topNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_moudle.top_num
     *
     * @param topNum the value for sys_rule_moudle.top_num
     *
     * @mbggenerated
     */
    public void setTopNum(Long topNum) {
        this.topNum = topNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_moudle.moudle_father
     *
     * @return the value of sys_rule_moudle.moudle_father
     *
     * @mbggenerated
     */
    public Long getMoudleFather() {
        return moudleFather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_moudle.moudle_father
     *
     * @param moudleFather the value for sys_rule_moudle.moudle_father
     *
     * @mbggenerated
     */
    public void setMoudleFather(Long moudleFather) {
        this.moudleFather = moudleFather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_moudle.moudle_name
     *
     * @return the value of sys_rule_moudle.moudle_name
     *
     * @mbggenerated
     */
    public String getMoudleName() {
        return moudleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_moudle.moudle_name
     *
     * @param moudleName the value for sys_rule_moudle.moudle_name
     *
     * @mbggenerated
     */
    public void setMoudleName(String moudleName) {
        this.moudleName = moudleName == null ? null : moudleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_moudle.moudle_desc
     *
     * @return the value of sys_rule_moudle.moudle_desc
     *
     * @mbggenerated
     */
    public String getMoudleDesc() {
        return moudleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_moudle.moudle_desc
     *
     * @param moudleDesc the value for sys_rule_moudle.moudle_desc
     *
     * @mbggenerated
     */
    public void setMoudleDesc(String moudleDesc) {
        this.moudleDesc = moudleDesc == null ? null : moudleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_moudle.create_user
     *
     * @return the value of sys_rule_moudle.create_user
     *
     * @mbggenerated
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_moudle.create_user
     *
     * @param createUser the value for sys_rule_moudle.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_moudle.create_time
     *
     * @return the value of sys_rule_moudle.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_moudle.create_time
     *
     * @param createTime the value for sys_rule_moudle.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_moudle.update_user
     *
     * @return the value of sys_rule_moudle.update_user
     *
     * @mbggenerated
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_moudle.update_user
     *
     * @param updateUser the value for sys_rule_moudle.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_moudle.update_time
     *
     * @return the value of sys_rule_moudle.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_moudle.update_time
     *
     * @param updateTime the value for sys_rule_moudle.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_moudle.is_enable
     *
     * @return the value of sys_rule_moudle.is_enable
     *
     * @mbggenerated
     */
    public Short getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_moudle.is_enable
     *
     * @param isEnable the value for sys_rule_moudle.is_enable
     *
     * @mbggenerated
     */
    public void setIsEnable(Short isEnable) {
        this.isEnable = isEnable;
    }
}