package com.buyauto.entity.sys;

import java.util.Date;

public class SysRulePrivilege {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_privilege.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_privilege.privilege_master
     *
     * @mbggenerated
     */
    private Integer privilegeMaster;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_privilege.privilege_id
     *
     * @mbggenerated
     */
    private Long privilegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_privilege.rule_type
     *
     * @mbggenerated
     */
    private Integer ruleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_privilege.rule_id
     *
     * @mbggenerated
     */
    private Long ruleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_privilege.is_enable
     *
     * @mbggenerated
     */
    private Short isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_privilege.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_privilege.create_user
     *
     * @mbggenerated
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_privilege.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule_privilege.update_user
     *
     * @mbggenerated
     */
    private Long updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_privilege.id
     *
     * @return the value of sys_rule_privilege.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_privilege.id
     *
     * @param id the value for sys_rule_privilege.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_privilege.privilege_master
     *
     * @return the value of sys_rule_privilege.privilege_master
     *
     * @mbggenerated
     */
    public Integer getPrivilegeMaster() {
        return privilegeMaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_privilege.privilege_master
     *
     * @param privilegeMaster the value for sys_rule_privilege.privilege_master
     *
     * @mbggenerated
     */
    public void setPrivilegeMaster(Integer privilegeMaster) {
        this.privilegeMaster = privilegeMaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_privilege.privilege_id
     *
     * @return the value of sys_rule_privilege.privilege_id
     *
     * @mbggenerated
     */
    public Long getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_privilege.privilege_id
     *
     * @param privilegeId the value for sys_rule_privilege.privilege_id
     *
     * @mbggenerated
     */
    public void setPrivilegeId(Long privilegeId) {
        this.privilegeId = privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_privilege.rule_type
     *
     * @return the value of sys_rule_privilege.rule_type
     *
     * @mbggenerated
     */
    public Integer getRuleType() {
        return ruleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_privilege.rule_type
     *
     * @param ruleType the value for sys_rule_privilege.rule_type
     *
     * @mbggenerated
     */
    public void setRuleType(Integer ruleType) {
        this.ruleType = ruleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_privilege.rule_id
     *
     * @return the value of sys_rule_privilege.rule_id
     *
     * @mbggenerated
     */
    public Long getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_privilege.rule_id
     *
     * @param ruleId the value for sys_rule_privilege.rule_id
     *
     * @mbggenerated
     */
    public void setRuleId(Long ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_privilege.is_enable
     *
     * @return the value of sys_rule_privilege.is_enable
     *
     * @mbggenerated
     */
    public Short getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_privilege.is_enable
     *
     * @param isEnable the value for sys_rule_privilege.is_enable
     *
     * @mbggenerated
     */
    public void setIsEnable(Short isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_privilege.create_time
     *
     * @return the value of sys_rule_privilege.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_privilege.create_time
     *
     * @param createTime the value for sys_rule_privilege.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_privilege.create_user
     *
     * @return the value of sys_rule_privilege.create_user
     *
     * @mbggenerated
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_privilege.create_user
     *
     * @param createUser the value for sys_rule_privilege.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_privilege.update_time
     *
     * @return the value of sys_rule_privilege.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_privilege.update_time
     *
     * @param updateTime the value for sys_rule_privilege.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule_privilege.update_user
     *
     * @return the value of sys_rule_privilege.update_user
     *
     * @mbggenerated
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule_privilege.update_user
     *
     * @param updateUser the value for sys_rule_privilege.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }
}