package com.buyauto.entity.sys;

import java.util.Date;

public class SysScheduled {
	
	/* job初始化程度 */
	public static final int INIT = Integer.valueOf(0);

	/* job运行状态 */
	public static final int RUNNING = Integer.valueOf(1);

	/* 成功 */
	public static final int SUCC = Integer.valueOf(2);

	/* 失败 */
	public static final int FAIL = Integer.valueOf(3);
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scheduled.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scheduled.job_name
     *
     * @mbggenerated
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scheduled.job_start
     *
     * @mbggenerated
     */
    private Date jobStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scheduled.job_end
     *
     * @mbggenerated
     */
    private Date jobEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scheduled.job_interval
     *
     * @mbggenerated
     */
    private Long jobInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scheduled.job_status
     *
     * @mbggenerated
     */
    private Integer jobStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scheduled.job_biz_name
     *
     * @mbggenerated
     */
    private String jobBizName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scheduled.job_biz_day
     *
     * @mbggenerated
     */
    private String jobBizDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scheduled.job_version
     *
     * @mbggenerated
     */
    private Integer jobVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scheduled.id
     *
     * @return the value of sys_scheduled.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scheduled.id
     *
     * @param id the value for sys_scheduled.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scheduled.job_name
     *
     * @return the value of sys_scheduled.job_name
     *
     * @mbggenerated
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scheduled.job_name
     *
     * @param jobName the value for sys_scheduled.job_name
     *
     * @mbggenerated
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scheduled.job_start
     *
     * @return the value of sys_scheduled.job_start
     *
     * @mbggenerated
     */
    public Date getJobStart() {
        return jobStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scheduled.job_start
     *
     * @param jobStart the value for sys_scheduled.job_start
     *
     * @mbggenerated
     */
    public void setJobStart(Date jobStart) {
        this.jobStart = jobStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scheduled.job_end
     *
     * @return the value of sys_scheduled.job_end
     *
     * @mbggenerated
     */
    public Date getJobEnd() {
        return jobEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scheduled.job_end
     *
     * @param jobEnd the value for sys_scheduled.job_end
     *
     * @mbggenerated
     */
    public void setJobEnd(Date jobEnd) {
        this.jobEnd = jobEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scheduled.job_interval
     *
     * @return the value of sys_scheduled.job_interval
     *
     * @mbggenerated
     */
    public Long getJobInterval() {
        return jobInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scheduled.job_interval
     *
     * @param jobInterval the value for sys_scheduled.job_interval
     *
     * @mbggenerated
     */
    public void setJobInterval(Long jobInterval) {
        this.jobInterval = jobInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scheduled.job_status
     *
     * @return the value of sys_scheduled.job_status
     *
     * @mbggenerated
     */
    public Integer getJobStatus() {
        return jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scheduled.job_status
     *
     * @param jobStatus the value for sys_scheduled.job_status
     *
     * @mbggenerated
     */
    public void setJobStatus(Integer jobStatus) {
        this.jobStatus = jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scheduled.job_biz_name
     *
     * @return the value of sys_scheduled.job_biz_name
     *
     * @mbggenerated
     */
    public String getJobBizName() {
        return jobBizName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scheduled.job_biz_name
     *
     * @param jobBizName the value for sys_scheduled.job_biz_name
     *
     * @mbggenerated
     */
    public void setJobBizName(String jobBizName) {
        this.jobBizName = jobBizName == null ? null : jobBizName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scheduled.job_biz_day
     *
     * @return the value of sys_scheduled.job_biz_day
     *
     * @mbggenerated
     */
    public String getJobBizDay() {
        return jobBizDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scheduled.job_biz_day
     *
     * @param jobBizDay the value for sys_scheduled.job_biz_day
     *
     * @mbggenerated
     */
    public void setJobBizDay(String jobBizDay) {
        this.jobBizDay = jobBizDay == null ? null : jobBizDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scheduled.job_version
     *
     * @return the value of sys_scheduled.job_version
     *
     * @mbggenerated
     */
    public Integer getJobVersion() {
        return jobVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scheduled.job_version
     *
     * @param jobVersion the value for sys_scheduled.job_version
     *
     * @mbggenerated
     */
    public void setJobVersion(Integer jobVersion) {
        this.jobVersion = jobVersion;
    }
}