package com.buyauto.entity.user;

import java.util.Date;

public class TUsersRecommender {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users_recommender.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users_recommender.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users_recommender.user_phone
     *
     * @mbggenerated
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users_recommender.father_id
     *
     * @mbggenerated
     */
    private Long fatherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users_recommender.father_phone
     *
     * @mbggenerated
     */
    private String fatherPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users_recommender.create_date
     *
     * @mbggenerated
     */
    private Date createDate;
    private Long grandpaId;
    private String grandpaPhone;
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users_recommender.id
     *
     * @param id the value for t_users_recommender.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users_recommender.user_id
     *
     * @return the value of t_users_recommender.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users_recommender.user_id
     *
     * @param userId the value for t_users_recommender.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users_recommender.user_phone
     *
     * @return the value of t_users_recommender.user_phone
     *
     * @mbggenerated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users_recommender.user_phone
     *
     * @param userPhone the value for t_users_recommender.user_phone
     *
     * @mbggenerated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users_recommender.father_id
     *
     * @return the value of t_users_recommender.father_id
     *
     * @mbggenerated
     */
    public Long getFatherId() {
        return fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users_recommender.father_id
     *
     * @param fatherId the value for t_users_recommender.father_id
     *
     * @mbggenerated
     */
    public void setFatherId(Long fatherId) {
        this.fatherId = fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users_recommender.father_phone
     *
     * @return the value of t_users_recommender.father_phone
     *
     * @mbggenerated
     */
    public String getFatherPhone() {
        return fatherPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users_recommender.father_phone
     *
     * @param fatherPhone the value for t_users_recommender.father_phone
     *
     * @mbggenerated
     */
    public void setFatherPhone(String fatherPhone) {
        this.fatherPhone = fatherPhone == null ? null : fatherPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users_recommender.create_date
     *
     * @return the value of t_users_recommender.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users_recommender.create_date
     *
     * @param createDate the value for t_users_recommender.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

	public Long getGrandpaId() {
		return grandpaId;
	}

	public void setGrandpaId(Long grandpaId) {
		this.grandpaId = grandpaId;
	}

	public String getGrandpaPhone() {
		return grandpaPhone;
	}

	public void setGrandpaPhone(String grandpaPhone) {
		this.grandpaPhone = grandpaPhone;
	}
}