package com.buyauto.entity.user;

import java.util.Date;

public class TUsersMsg {

	private Long id;
    private Long userId;
    private String msgInfo;
    private Integer type;
    private Date createDate;
    private Integer status;
    
    
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users_msg.id
     *
     * @param id the value for t_users_msg.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users_msg.user_id
     *
     * @return the value of t_users_msg.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users_msg.user_id
     *
     * @param userId the value for t_users_msg.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users_msg.msg_info
     *
     * @return the value of t_users_msg.msg_info
     *
     * @mbggenerated
     */
    public String getMsgInfo() {
        return msgInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users_msg.msg_info
     *
     * @param msgInfo the value for t_users_msg.msg_info
     *
     * @mbggenerated
     */
    public void setMsgInfo(String msgInfo) {
        this.msgInfo = msgInfo == null ? null : msgInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users_msg.type
     *
     * @return the value of t_users_msg.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users_msg.type
     *
     * @param type the value for t_users_msg.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users_msg.create_date
     *
     * @return the value of t_users_msg.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users_msg.create_date
     *
     * @param createDate the value for t_users_msg.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users_msg.status
     *
     * @return the value of t_users_msg.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users_msg.status
     *
     * @param status the value for t_users_msg.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
    public TUsersMsg(){}
    public TUsersMsg(Long id,Long userId,String msgInfo,Integer type, Date createDate,Integer status){
    	this.id = id;
    	this.type = type;
    	this.userId = userId;
    	this.createDate = createDate;
    	this.msgInfo = msgInfo;
    	this.status = status;
    }
}