package com.buyauto.entity.cms;

import java.util.Date;

public class CmsBanner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.id
     *
     * @mbggenerated
     */
    private Long id;


	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.link
     *
     * @mbggenerated
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.order_num
     *
     * @mbggenerated
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.oper_id
     *
     * @mbggenerated
     */
    private Long operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.terminal
     *
     * @mbggenerated
     */
    private Integer terminal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.id
     *
     * @return the value of cms_banner.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.id
     *
     * @param id the value for cms_banner.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.title
     *
     * @return the value of cms_banner.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.title
     *
     * @param title the value for cms_banner.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.link
     *
     * @return the value of cms_banner.link
     *
     * @mbggenerated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.link
     *
     * @param link the value for cms_banner.link
     *
     * @mbggenerated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.image
     *
     * @return the value of cms_banner.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.image
     *
     * @param image the value for cms_banner.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.order_num
     *
     * @return the value of cms_banner.order_num
     *
     * @mbggenerated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.order_num
     *
     * @param orderNum the value for cms_banner.order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.type
     *
     * @return the value of cms_banner.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.type
     *
     * @param type the value for cms_banner.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.status
     *
     * @return the value of cms_banner.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.status
     *
     * @param status the value for cms_banner.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.create_time
     *
     * @return the value of cms_banner.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.create_time
     *
     * @param createTime the value for cms_banner.create_time
     *
     * @mbggenerated
     */
    public void UpdateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.update_time
     *
     * @return the value of cms_banner.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.update_time
     *
     * @param updateTime the value for cms_banner.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.oper_id
     *
     * @return the value of cms_banner.oper_id
     *
     * @mbggenerated
     */
    public Long getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.oper_id
     *
     * @param operId the value for cms_banner.oper_id
     *
     * @mbggenerated
     */
    public void setOperId(Long operId) {
        this.operId = operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.terminal
     *
     * @return the value of cms_banner.terminal
     *
     * @mbggenerated
     */
    public Integer getTerminal() {
        return terminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.terminal
     *
     * @param terminal the value for cms_banner.terminal
     *
     * @mbggenerated
     */
    public void setTerminal(Integer terminal) {
        this.terminal = terminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.version
     *
     * @return the value of cms_banner.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.version
     *
     * @param version the value for cms_banner.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
    public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}