package com.buyauto.entity.cms;

import java.io.Serializable;
import java.util.Date;

public class CmsNews implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -5574157988943629314L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news.id
     *
     * @mbggenerated
     */
    private Long newsId;

    public Long getNewsId() {
		return newsId;
	}

	public void setNewsId(Long newsId) {
		this.newsId = newsId;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news.is_top
     *
     * @mbggenerated
     */
    private Integer isTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news.order_num
     *
     * @mbggenerated
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news.is_hot
     *
     * @mbggenerated
     */
    private Integer isHot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news.introduction
     *
     * @mbggenerated
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news.pic
     *
     * @mbggenerated
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news.onlinetime
     *
     * @mbggenerated
     */
    private Date onlinetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news.oper_id
     *
     * @mbggenerated
     */
    private Long operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news.content
     *
     * @mbggenerated
     */
    private String content;

//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column cms_news.id
//     *
//     * @return the value of cms_news.id
//     *
//     * @mbggenerated
//     */
//    public Long getId() {
//        return newsId;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column cms_news.id
//     *
//     * @param id the value for cms_news.id
//     *
//     * @mbggenerated
//     */
//    public void setId(Long newsId) {
//        this.newsId = newsId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_news.is_top
     *
     * @return the value of cms_news.is_top
     *
     * @mbggenerated
     */
    public Integer getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_news.is_top
     *
     * @param isTop the value for cms_news.is_top
     *
     * @mbggenerated
     */
    public void setIsTop(Integer isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_news.order_num
     *
     * @return the value of cms_news.order_num
     *
     * @mbggenerated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_news.order_num
     *
     * @param orderNum the value for cms_news.order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_news.is_hot
     *
     * @return the value of cms_news.is_hot
     *
     * @mbggenerated
     */
    public Integer getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_news.is_hot
     *
     * @param isHot the value for cms_news.is_hot
     *
     * @mbggenerated
     */
    public void setIsHot(Integer isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_news.type
     *
     * @return the value of cms_news.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_news.type
     *
     * @param type the value for cms_news.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_news.title
     *
     * @return the value of cms_news.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_news.title
     *
     * @param title the value for cms_news.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_news.introduction
     *
     * @return the value of cms_news.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_news.introduction
     *
     * @param introduction the value for cms_news.introduction
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_news.pic
     *
     * @return the value of cms_news.pic
     *
     * @mbggenerated
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_news.pic
     *
     * @param pic the value for cms_news.pic
     *
     * @mbggenerated
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_news.onlinetime
     *
     * @return the value of cms_news.onlinetime
     *
     * @mbggenerated
     */
    public Date getOnlinetime() {
        return onlinetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_news.onlinetime
     *
     * @param onlinetime the value for cms_news.onlinetime
     *
     * @mbggenerated
     */
    public void setOnlinetime(Date onlinetime) {
        this.onlinetime = onlinetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_news.author
     *
     * @return the value of cms_news.author
     *
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_news.author
     *
     * @param author the value for cms_news.author
     *
     * @mbggenerated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_news.status
     *
     * @return the value of cms_news.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_news.status
     *
     * @param status the value for cms_news.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_news.update_time
     *
     * @return the value of cms_news.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_news.update_time
     *
     * @param updateTime the value for cms_news.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_news.create_time
     *
     * @return the value of cms_news.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_news.create_time
     *
     * @param createTime the value for cms_news.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_news.oper_id
     *
     * @return the value of cms_news.oper_id
     *
     * @mbggenerated
     */
    public Long getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_news.oper_id
     *
     * @param operId the value for cms_news.oper_id
     *
     * @mbggenerated
     */
    public void setOperId(Long operId) {
        this.operId = operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_news.version
     *
     * @return the value of cms_news.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_news.version
     *
     * @param version the value for cms_news.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_news.content
     *
     * @return the value of cms_news.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_news.content
     *
     * @param content the value for cms_news.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}