package com.buyauto.entity.products;

import java.io.Serializable;
import java.util.Date;

public class TProductsImage implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -3981347771141547087L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_image.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_image.product_id
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_image.file_name
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_image.file_path
     *
     * @mbggenerated
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_image.file_path_s
     *
     * @mbggenerated
     */
    private String filePathS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_image.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_image.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_image.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_image.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_image.id
     *
     * @return the value of t_products_image.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_image.id
     *
     * @param id the value for t_products_image.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_image.product_id
     *
     * @return the value of t_products_image.product_id
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_image.product_id
     *
     * @param productId the value for t_products_image.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_image.file_name
     *
     * @return the value of t_products_image.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_image.file_name
     *
     * @param fileName the value for t_products_image.file_name
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_image.file_path
     *
     * @return the value of t_products_image.file_path
     *
     * @mbggenerated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_image.file_path
     *
     * @param filePath the value for t_products_image.file_path
     *
     * @mbggenerated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_image.file_path_s
     *
     * @return the value of t_products_image.file_path_s
     *
     * @mbggenerated
     */
    public String getFilePathS() {
        return filePathS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_image.file_path_s
     *
     * @param filePathS the value for t_products_image.file_path_s
     *
     * @mbggenerated
     */
    public void setFilePathS(String filePathS) {
        this.filePathS = filePathS == null ? null : filePathS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_image.type
     *
     * @return the value of t_products_image.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_image.type
     *
     * @param type the value for t_products_image.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_image.create_date
     *
     * @return the value of t_products_image.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_image.create_date
     *
     * @param createDate the value for t_products_image.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_image.status
     *
     * @return the value of t_products_image.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_image.status
     *
     * @param status the value for t_products_image.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_image.version
     *
     * @return the value of t_products_image.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_image.version
     *
     * @param version the value for t_products_image.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}