package com.buyauto.entity.products;


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TProducts implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1873439048673512493L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.products_id
     *
     * @mbggenerated
     */
    private Long productsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.brand_id
     *
     * @mbggenerated
     */
    private Long brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.car_type
     *
     * @mbggenerated
     */
    private Integer carType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.price_range
     *
     * @mbggenerated
     */
    private Integer priceRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.position
     *
     * @mbggenerated
     */
    private Integer position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.car_model
     *
     * @mbggenerated
     */
    private String carModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.out_color
     *
     * @mbggenerated
     */
    private String outColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.in_color
     *
     * @mbggenerated
     */
    private String inColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.country
     *
     * @mbggenerated
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.power
     *
     * @mbggenerated
     */
    private String power;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.engine
     *
     * @mbggenerated
     */
    private String engine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.factory_date
     *
     * @mbggenerated
     */
    private Date factoryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.china_price
     *
     * @mbggenerated
     */
    private BigDecimal chinaPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.basic_configure
     *
     * @mbggenerated
     */
    private String basicConfigure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.must_configure
     *
     * @mbggenerated
     */
    private String mustConfigure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.optional_configure
     *
     * @mbggenerated
     */
    private String optionalConfigure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.car_price
     *
     * @mbggenerated
     */
    private BigDecimal carPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.must_configure_price
     *
     * @mbggenerated
     */
    private BigDecimal mustConfigurePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.recommend
     *
     * @mbggenerated
     */
    private Integer recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.stock
     *
     * @mbggenerated
     */
    private Integer stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.gearbox
     *
     * @mbggenerated
     */
    private String gearbox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.deposit
     *
     * @mbggenerated
     */
    private Integer deposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.oper_id
     *
     * @mbggenerated
     */
    private Long operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.doors
     *
     * @mbggenerated
     */
    private String doors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.seats
     *
     * @mbggenerated
     */
    private String seats;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.car_standards
     *
     * @mbggenerated
     */
    private String carStandards;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.self_support
     *
     * @mbggenerated
     */
    private Integer selfSupport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.personal
     *
     * @mbggenerated
     */
    private BigDecimal personal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.sales
     *
     * @mbggenerated
     */
    private BigDecimal sales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.distributor
     *
     * @mbggenerated
     */
    private BigDecimal distributor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.products_id
     *
     * @return the value of t_products.products_id
     *
     * @mbggenerated
     */
    public Long getProductsId() {
        return productsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.products_id
     *
     * @param productsId the value for t_products.products_id
     *
     * @mbggenerated
     */
    public void setProductsId(Long productsId) {
        this.productsId = productsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.brand_id
     *
     * @return the value of t_products.brand_id
     *
     * @mbggenerated
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.brand_id
     *
     * @param brandId the value for t_products.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.car_type
     *
     * @return the value of t_products.car_type
     *
     * @mbggenerated
     */
    public Integer getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.car_type
     *
     * @param carType the value for t_products.car_type
     *
     * @mbggenerated
     */
    public void setCarType(Integer carType) {
        this.carType = carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.price_range
     *
     * @return the value of t_products.price_range
     *
     * @mbggenerated
     */
    public Integer getPriceRange() {
        return priceRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.price_range
     *
     * @param priceRange the value for t_products.price_range
     *
     * @mbggenerated
     */
    public void setPriceRange(Integer priceRange) {
        this.priceRange = priceRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.position
     *
     * @return the value of t_products.position
     *
     * @mbggenerated
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.position
     *
     * @param position the value for t_products.position
     *
     * @mbggenerated
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.title
     *
     * @return the value of t_products.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.title
     *
     * @param title the value for t_products.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.car_model
     *
     * @return the value of t_products.car_model
     *
     * @mbggenerated
     */
    public String getCarModel() {
        return carModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.car_model
     *
     * @param carModel the value for t_products.car_model
     *
     * @mbggenerated
     */
    public void setCarModel(String carModel) {
        this.carModel = carModel == null ? null : carModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.out_color
     *
     * @return the value of t_products.out_color
     *
     * @mbggenerated
     */
    public String getOutColor() {
        return outColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.out_color
     *
     * @param outColor the value for t_products.out_color
     *
     * @mbggenerated
     */
    public void setOutColor(String outColor) {
        this.outColor = outColor == null ? null : outColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.in_color
     *
     * @return the value of t_products.in_color
     *
     * @mbggenerated
     */
    public String getInColor() {
        return inColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.in_color
     *
     * @param inColor the value for t_products.in_color
     *
     * @mbggenerated
     */
    public void setInColor(String inColor) {
        this.inColor = inColor == null ? null : inColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.country
     *
     * @return the value of t_products.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.country
     *
     * @param country the value for t_products.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.power
     *
     * @return the value of t_products.power
     *
     * @mbggenerated
     */
    public String getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.power
     *
     * @param power the value for t_products.power
     *
     * @mbggenerated
     */
    public void setPower(String power) {
        this.power = power == null ? null : power.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.engine
     *
     * @return the value of t_products.engine
     *
     * @mbggenerated
     */
    public String getEngine() {
        return engine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.engine
     *
     * @param engine the value for t_products.engine
     *
     * @mbggenerated
     */
    public void setEngine(String engine) {
        this.engine = engine == null ? null : engine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.factory_date
     *
     * @return the value of t_products.factory_date
     *
     * @mbggenerated
     */
    public Date getFactoryDate() {
        return factoryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.factory_date
     *
     * @param factoryDate the value for t_products.factory_date
     *
     * @mbggenerated
     */
    public void setFactoryDate(Date factoryDate) {
        this.factoryDate = factoryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.china_price
     *
     * @return the value of t_products.china_price
     *
     * @mbggenerated
     */
    public BigDecimal getChinaPrice() {
        return chinaPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.china_price
     *
     * @param chinaPrice the value for t_products.china_price
     *
     * @mbggenerated
     */
    public void setChinaPrice(BigDecimal chinaPrice) {
        this.chinaPrice = chinaPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.basic_configure
     *
     * @return the value of t_products.basic_configure
     *
     * @mbggenerated
     */
    public String getBasicConfigure() {
        return basicConfigure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.basic_configure
     *
     * @param basicConfigure the value for t_products.basic_configure
     *
     * @mbggenerated
     */
    public void setBasicConfigure(String basicConfigure) {
        this.basicConfigure = basicConfigure == null ? null : basicConfigure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.must_configure
     *
     * @return the value of t_products.must_configure
     *
     * @mbggenerated
     */
    public String getMustConfigure() {
        return mustConfigure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.must_configure
     *
     * @param mustConfigure the value for t_products.must_configure
     *
     * @mbggenerated
     */
    public void setMustConfigure(String mustConfigure) {
        this.mustConfigure = mustConfigure == null ? null : mustConfigure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.optional_configure
     *
     * @return the value of t_products.optional_configure
     *
     * @mbggenerated
     */
    public String getOptionalConfigure() {
        return optionalConfigure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.optional_configure
     *
     * @param optionalConfigure the value for t_products.optional_configure
     *
     * @mbggenerated
     */
    public void setOptionalConfigure(String optionalConfigure) {
        this.optionalConfigure = optionalConfigure == null ? null : optionalConfigure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.car_price
     *
     * @return the value of t_products.car_price
     *
     * @mbggenerated
     */
    public BigDecimal getCarPrice() {
        return carPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.car_price
     *
     * @param carPrice the value for t_products.car_price
     *
     * @mbggenerated
     */
    public void setCarPrice(BigDecimal carPrice) {
        this.carPrice = carPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.must_configure_price
     *
     * @return the value of t_products.must_configure_price
     *
     * @mbggenerated
     */
    public BigDecimal getMustConfigurePrice() {
        return mustConfigurePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.must_configure_price
     *
     * @param mustConfigurePrice the value for t_products.must_configure_price
     *
     * @mbggenerated
     */
    public void setMustConfigurePrice(BigDecimal mustConfigurePrice) {
        this.mustConfigurePrice = mustConfigurePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.status
     *
     * @return the value of t_products.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.status
     *
     * @param status the value for t_products.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.recommend
     *
     * @return the value of t_products.recommend
     *
     * @mbggenerated
     */
    public Integer getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.recommend
     *
     * @param recommend the value for t_products.recommend
     *
     * @mbggenerated
     */
    public void setRecommend(Integer recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.stock
     *
     * @return the value of t_products.stock
     *
     * @mbggenerated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.stock
     *
     * @param stock the value for t_products.stock
     *
     * @mbggenerated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.gearbox
     *
     * @return the value of t_products.gearbox
     *
     * @mbggenerated
     */
    public String getGearbox() {
        return gearbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.gearbox
     *
     * @param gearbox the value for t_products.gearbox
     *
     * @mbggenerated
     */
    public void setGearbox(String gearbox) {
        this.gearbox = gearbox == null ? null : gearbox.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.deposit
     *
     * @return the value of t_products.deposit
     *
     * @mbggenerated
     */
    public Integer getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.deposit
     *
     * @param deposit the value for t_products.deposit
     *
     * @mbggenerated
     */
    public void setDeposit(Integer deposit) {
        this.deposit = deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.create_date
     *
     * @return the value of t_products.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.create_date
     *
     * @param createDate the value for t_products.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.oper_id
     *
     * @return the value of t_products.oper_id
     *
     * @mbggenerated
     */
    public Long getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.oper_id
     *
     * @param operId the value for t_products.oper_id
     *
     * @mbggenerated
     */
    public void setOperId(Long operId) {
        this.operId = operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.update_date
     *
     * @return the value of t_products.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.update_date
     *
     * @param updateDate the value for t_products.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.version
     *
     * @return the value of t_products.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.version
     *
     * @param version the value for t_products.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.doors
     *
     * @return the value of t_products.doors
     *
     * @mbggenerated
     */
    public String getDoors() {
        return doors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.doors
     *
     * @param doors the value for t_products.doors
     *
     * @mbggenerated
     */
    public void setDoors(String doors) {
        this.doors = doors == null ? null : doors.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.seats
     *
     * @return the value of t_products.seats
     *
     * @mbggenerated
     */
    public String getSeats() {
        return seats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.seats
     *
     * @param seats the value for t_products.seats
     *
     * @mbggenerated
     */
    public void setSeats(String seats) {
        this.seats = seats == null ? null : seats.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.remarks
     *
     * @return the value of t_products.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.remarks
     *
     * @param remarks the value for t_products.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.car_standards
     *
     * @return the value of t_products.car_standards
     *
     * @mbggenerated
     */
    public String getCarStandards() {
        return carStandards;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.car_standards
     *
     * @param carStandards the value for t_products.car_standards
     *
     * @mbggenerated
     */
    public void setCarStandards(String carStandards) {
        this.carStandards = carStandards == null ? null : carStandards.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.self_support
     *
     * @return the value of t_products.self_support
     *
     * @mbggenerated
     */
    public Integer getSelfSupport() {
        return selfSupport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.self_support
     *
     * @param selfSupport the value for t_products.self_support
     *
     * @mbggenerated
     */
    public void setSelfSupport(Integer selfSupport) {
        this.selfSupport = selfSupport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.personal
     *
     * @return the value of t_products.personal
     *
     * @mbggenerated
     */
    public BigDecimal getPersonal() {
        return personal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.personal
     *
     * @param personal the value for t_products.personal
     *
     * @mbggenerated
     */
    public void setPersonal(BigDecimal personal) {
        this.personal = personal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.sales
     *
     * @return the value of t_products.sales
     *
     * @mbggenerated
     */
    public BigDecimal getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.sales
     *
     * @param sales the value for t_products.sales
     *
     * @mbggenerated
     */
    public void setSales(BigDecimal sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.distributor
     *
     * @return the value of t_products.distributor
     *
     * @mbggenerated
     */
    public BigDecimal getDistributor() {
        return distributor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.distributor
     *
     * @param distributor the value for t_products.distributor
     *
     * @mbggenerated
     */
    public void setDistributor(BigDecimal distributor) {
        this.distributor = distributor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products.content
     *
     * @return the value of t_products.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products.content
     *
     * @param content the value for t_products.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}