package com.buyauto.entity.products;


import java.util.Date;

public class TProductsTemp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.car_no
     *
     * @mbggenerated
     */
    private String carNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.brand
     *
     * @mbggenerated
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.cargo_code
     *
     * @mbggenerated
     */
    private String cargoCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.cargo_name_cn
     *
     * @mbggenerated
     */
    private String cargoNameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.cargo_name_en
     *
     * @mbggenerated
     */
    private String cargoNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.car_type
     *
     * @mbggenerated
     */
    private String carType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.order_model
     *
     * @mbggenerated
     */
    private String orderModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.car_model
     *
     * @mbggenerated
     */
    private String carModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.out_color
     *
     * @mbggenerated
     */
    private String outColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.in_color
     *
     * @mbggenerated
     */
    private String inColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.car_standards
     *
     * @mbggenerated
     */
    private String carStandards;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.country
     *
     * @mbggenerated
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.power
     *
     * @mbggenerated
     */
    private String power;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.engine
     *
     * @mbggenerated
     */
    private String engine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.factory_date
     *
     * @mbggenerated
     */
    private String factoryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.doors
     *
     * @mbggenerated
     */
    private String doors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.seats
     *
     * @mbggenerated
     */
    private String seats;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.car_price
     *
     * @mbggenerated
     */
    private String carPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.must_configure
     *
     * @mbggenerated
     */
    private String mustConfigure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.must_configure_price
     *
     * @mbggenerated
     */
    private String mustConfigurePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.optional_configure
     *
     * @mbggenerated
     */
    private String optionalConfigure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.optional_configure_price1
     *
     * @mbggenerated
     */
    private String optionalConfigurePrice1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.optional_configure_price2
     *
     * @mbggenerated
     */
    private String optionalConfigurePrice2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.optional_configure_price3
     *
     * @mbggenerated
     */
    private String optionalConfigurePrice3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.optional_configure_price4
     *
     * @mbggenerated
     */
    private String optionalConfigurePrice4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.optional_configure_price5
     *
     * @mbggenerated
     */
    private String optionalConfigurePrice5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.optional_configure_price6
     *
     * @mbggenerated
     */
    private String optionalConfigurePrice6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.optional_configure_price7
     *
     * @mbggenerated
     */
    private String optionalConfigurePrice7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.optional_configure_price8
     *
     * @mbggenerated
     */
    private String optionalConfigurePrice8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.optional_configure_price9
     *
     * @mbggenerated
     */
    private String optionalConfigurePrice9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.optional_configure_price10
     *
     * @mbggenerated
     */
    private String optionalConfigurePrice10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.execute_date
     *
     * @mbggenerated
     */
    private Date executeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_products_temp.logistics
     *
     * @mbggenerated
     */
    private String logistics;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.id
     *
     * @return the value of t_products_temp.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.id
     *
     * @param id the value for t_products_temp.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.car_no
     *
     * @return the value of t_products_temp.car_no
     *
     * @mbggenerated
     */
    public String getCarNo() {
        return carNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.car_no
     *
     * @param carNo the value for t_products_temp.car_no
     *
     * @mbggenerated
     */
    public void setCarNo(String carNo) {
        this.carNo = carNo == null ? null : carNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.brand
     *
     * @return the value of t_products_temp.brand
     *
     * @mbggenerated
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.brand
     *
     * @param brand the value for t_products_temp.brand
     *
     * @mbggenerated
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.cargo_code
     *
     * @return the value of t_products_temp.cargo_code
     *
     * @mbggenerated
     */
    public String getCargoCode() {
        return cargoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.cargo_code
     *
     * @param cargoCode the value for t_products_temp.cargo_code
     *
     * @mbggenerated
     */
    public void setCargoCode(String cargoCode) {
        this.cargoCode = cargoCode == null ? null : cargoCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.cargo_name_cn
     *
     * @return the value of t_products_temp.cargo_name_cn
     *
     * @mbggenerated
     */
    public String getCargoNameCn() {
        return cargoNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.cargo_name_cn
     *
     * @param cargoNameCn the value for t_products_temp.cargo_name_cn
     *
     * @mbggenerated
     */
    public void setCargoNameCn(String cargoNameCn) {
        this.cargoNameCn = cargoNameCn == null ? null : cargoNameCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.cargo_name_en
     *
     * @return the value of t_products_temp.cargo_name_en
     *
     * @mbggenerated
     */
    public String getCargoNameEn() {
        return cargoNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.cargo_name_en
     *
     * @param cargoNameEn the value for t_products_temp.cargo_name_en
     *
     * @mbggenerated
     */
    public void setCargoNameEn(String cargoNameEn) {
        this.cargoNameEn = cargoNameEn == null ? null : cargoNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.car_type
     *
     * @return the value of t_products_temp.car_type
     *
     * @mbggenerated
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.car_type
     *
     * @param carType the value for t_products_temp.car_type
     *
     * @mbggenerated
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.order_model
     *
     * @return the value of t_products_temp.order_model
     *
     * @mbggenerated
     */
    public String getOrderModel() {
        return orderModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.order_model
     *
     * @param orderModel the value for t_products_temp.order_model
     *
     * @mbggenerated
     */
    public void setOrderModel(String orderModel) {
        this.orderModel = orderModel == null ? null : orderModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.position
     *
     * @return the value of t_products_temp.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.position
     *
     * @param position the value for t_products_temp.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.car_model
     *
     * @return the value of t_products_temp.car_model
     *
     * @mbggenerated
     */
    public String getCarModel() {
        return carModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.car_model
     *
     * @param carModel the value for t_products_temp.car_model
     *
     * @mbggenerated
     */
    public void setCarModel(String carModel) {
        this.carModel = carModel == null ? null : carModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.out_color
     *
     * @return the value of t_products_temp.out_color
     *
     * @mbggenerated
     */
    public String getOutColor() {
        return outColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.out_color
     *
     * @param outColor the value for t_products_temp.out_color
     *
     * @mbggenerated
     */
    public void setOutColor(String outColor) {
        this.outColor = outColor == null ? null : outColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.in_color
     *
     * @return the value of t_products_temp.in_color
     *
     * @mbggenerated
     */
    public String getInColor() {
        return inColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.in_color
     *
     * @param inColor the value for t_products_temp.in_color
     *
     * @mbggenerated
     */
    public void setInColor(String inColor) {
        this.inColor = inColor == null ? null : inColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.car_standards
     *
     * @return the value of t_products_temp.car_standards
     *
     * @mbggenerated
     */
    public String getCarStandards() {
        return carStandards;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.car_standards
     *
     * @param carStandards the value for t_products_temp.car_standards
     *
     * @mbggenerated
     */
    public void setCarStandards(String carStandards) {
        this.carStandards = carStandards == null ? null : carStandards.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.country
     *
     * @return the value of t_products_temp.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.country
     *
     * @param country the value for t_products_temp.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.power
     *
     * @return the value of t_products_temp.power
     *
     * @mbggenerated
     */
    public String getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.power
     *
     * @param power the value for t_products_temp.power
     *
     * @mbggenerated
     */
    public void setPower(String power) {
        this.power = power == null ? null : power.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.engine
     *
     * @return the value of t_products_temp.engine
     *
     * @mbggenerated
     */
    public String getEngine() {
        return engine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.engine
     *
     * @param engine the value for t_products_temp.engine
     *
     * @mbggenerated
     */
    public void setEngine(String engine) {
        this.engine = engine == null ? null : engine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.factory_date
     *
     * @return the value of t_products_temp.factory_date
     *
     * @mbggenerated
     */
    public String getFactoryDate() {
        return factoryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.factory_date
     *
     * @param factoryDate the value for t_products_temp.factory_date
     *
     * @mbggenerated
     */
    public void setFactoryDate(String factoryDate) {
        this.factoryDate = factoryDate == null ? null : factoryDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.doors
     *
     * @return the value of t_products_temp.doors
     *
     * @mbggenerated
     */
    public String getDoors() {
        return doors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.doors
     *
     * @param doors the value for t_products_temp.doors
     *
     * @mbggenerated
     */
    public void setDoors(String doors) {
        this.doors = doors == null ? null : doors.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.seats
     *
     * @return the value of t_products_temp.seats
     *
     * @mbggenerated
     */
    public String getSeats() {
        return seats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.seats
     *
     * @param seats the value for t_products_temp.seats
     *
     * @mbggenerated
     */
    public void setSeats(String seats) {
        this.seats = seats == null ? null : seats.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.remarks
     *
     * @return the value of t_products_temp.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.remarks
     *
     * @param remarks the value for t_products_temp.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.car_price
     *
     * @return the value of t_products_temp.car_price
     *
     * @mbggenerated
     */
    public String getCarPrice() {
        return carPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.car_price
     *
     * @param carPrice the value for t_products_temp.car_price
     *
     * @mbggenerated
     */
    public void setCarPrice(String carPrice) {
        this.carPrice = carPrice == null ? null : carPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.must_configure
     *
     * @return the value of t_products_temp.must_configure
     *
     * @mbggenerated
     */
    public String getMustConfigure() {
        return mustConfigure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.must_configure
     *
     * @param mustConfigure the value for t_products_temp.must_configure
     *
     * @mbggenerated
     */
    public void setMustConfigure(String mustConfigure) {
        this.mustConfigure = mustConfigure == null ? null : mustConfigure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.must_configure_price
     *
     * @return the value of t_products_temp.must_configure_price
     *
     * @mbggenerated
     */
    public String getMustConfigurePrice() {
        return mustConfigurePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.must_configure_price
     *
     * @param mustConfigurePrice the value for t_products_temp.must_configure_price
     *
     * @mbggenerated
     */
    public void setMustConfigurePrice(String mustConfigurePrice) {
        this.mustConfigurePrice = mustConfigurePrice == null ? null : mustConfigurePrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.optional_configure
     *
     * @return the value of t_products_temp.optional_configure
     *
     * @mbggenerated
     */
    public String getOptionalConfigure() {
        return optionalConfigure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.optional_configure
     *
     * @param optionalConfigure the value for t_products_temp.optional_configure
     *
     * @mbggenerated
     */
    public void setOptionalConfigure(String optionalConfigure) {
        this.optionalConfigure = optionalConfigure == null ? null : optionalConfigure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.optional_configure_price1
     *
     * @return the value of t_products_temp.optional_configure_price1
     *
     * @mbggenerated
     */
    public String getOptionalConfigurePrice1() {
        return optionalConfigurePrice1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.optional_configure_price1
     *
     * @param optionalConfigurePrice1 the value for t_products_temp.optional_configure_price1
     *
     * @mbggenerated
     */
    public void setOptionalConfigurePrice1(String optionalConfigurePrice1) {
        this.optionalConfigurePrice1 = optionalConfigurePrice1 == null ? null : optionalConfigurePrice1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.optional_configure_price2
     *
     * @return the value of t_products_temp.optional_configure_price2
     *
     * @mbggenerated
     */
    public String getOptionalConfigurePrice2() {
        return optionalConfigurePrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.optional_configure_price2
     *
     * @param optionalConfigurePrice2 the value for t_products_temp.optional_configure_price2
     *
     * @mbggenerated
     */
    public void setOptionalConfigurePrice2(String optionalConfigurePrice2) {
        this.optionalConfigurePrice2 = optionalConfigurePrice2 == null ? null : optionalConfigurePrice2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.optional_configure_price3
     *
     * @return the value of t_products_temp.optional_configure_price3
     *
     * @mbggenerated
     */
    public String getOptionalConfigurePrice3() {
        return optionalConfigurePrice3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.optional_configure_price3
     *
     * @param optionalConfigurePrice3 the value for t_products_temp.optional_configure_price3
     *
     * @mbggenerated
     */
    public void setOptionalConfigurePrice3(String optionalConfigurePrice3) {
        this.optionalConfigurePrice3 = optionalConfigurePrice3 == null ? null : optionalConfigurePrice3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.optional_configure_price4
     *
     * @return the value of t_products_temp.optional_configure_price4
     *
     * @mbggenerated
     */
    public String getOptionalConfigurePrice4() {
        return optionalConfigurePrice4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.optional_configure_price4
     *
     * @param optionalConfigurePrice4 the value for t_products_temp.optional_configure_price4
     *
     * @mbggenerated
     */
    public void setOptionalConfigurePrice4(String optionalConfigurePrice4) {
        this.optionalConfigurePrice4 = optionalConfigurePrice4 == null ? null : optionalConfigurePrice4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.optional_configure_price5
     *
     * @return the value of t_products_temp.optional_configure_price5
     *
     * @mbggenerated
     */
    public String getOptionalConfigurePrice5() {
        return optionalConfigurePrice5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.optional_configure_price5
     *
     * @param optionalConfigurePrice5 the value for t_products_temp.optional_configure_price5
     *
     * @mbggenerated
     */
    public void setOptionalConfigurePrice5(String optionalConfigurePrice5) {
        this.optionalConfigurePrice5 = optionalConfigurePrice5 == null ? null : optionalConfigurePrice5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.optional_configure_price6
     *
     * @return the value of t_products_temp.optional_configure_price6
     *
     * @mbggenerated
     */
    public String getOptionalConfigurePrice6() {
        return optionalConfigurePrice6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.optional_configure_price6
     *
     * @param optionalConfigurePrice6 the value for t_products_temp.optional_configure_price6
     *
     * @mbggenerated
     */
    public void setOptionalConfigurePrice6(String optionalConfigurePrice6) {
        this.optionalConfigurePrice6 = optionalConfigurePrice6 == null ? null : optionalConfigurePrice6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.optional_configure_price7
     *
     * @return the value of t_products_temp.optional_configure_price7
     *
     * @mbggenerated
     */
    public String getOptionalConfigurePrice7() {
        return optionalConfigurePrice7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.optional_configure_price7
     *
     * @param optionalConfigurePrice7 the value for t_products_temp.optional_configure_price7
     *
     * @mbggenerated
     */
    public void setOptionalConfigurePrice7(String optionalConfigurePrice7) {
        this.optionalConfigurePrice7 = optionalConfigurePrice7 == null ? null : optionalConfigurePrice7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.optional_configure_price8
     *
     * @return the value of t_products_temp.optional_configure_price8
     *
     * @mbggenerated
     */
    public String getOptionalConfigurePrice8() {
        return optionalConfigurePrice8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.optional_configure_price8
     *
     * @param optionalConfigurePrice8 the value for t_products_temp.optional_configure_price8
     *
     * @mbggenerated
     */
    public void setOptionalConfigurePrice8(String optionalConfigurePrice8) {
        this.optionalConfigurePrice8 = optionalConfigurePrice8 == null ? null : optionalConfigurePrice8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.optional_configure_price9
     *
     * @return the value of t_products_temp.optional_configure_price9
     *
     * @mbggenerated
     */
    public String getOptionalConfigurePrice9() {
        return optionalConfigurePrice9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.optional_configure_price9
     *
     * @param optionalConfigurePrice9 the value for t_products_temp.optional_configure_price9
     *
     * @mbggenerated
     */
    public void setOptionalConfigurePrice9(String optionalConfigurePrice9) {
        this.optionalConfigurePrice9 = optionalConfigurePrice9 == null ? null : optionalConfigurePrice9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.optional_configure_price10
     *
     * @return the value of t_products_temp.optional_configure_price10
     *
     * @mbggenerated
     */
    public String getOptionalConfigurePrice10() {
        return optionalConfigurePrice10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.optional_configure_price10
     *
     * @param optionalConfigurePrice10 the value for t_products_temp.optional_configure_price10
     *
     * @mbggenerated
     */
    public void setOptionalConfigurePrice10(String optionalConfigurePrice10) {
        this.optionalConfigurePrice10 = optionalConfigurePrice10 == null ? null : optionalConfigurePrice10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.create_date
     *
     * @return the value of t_products_temp.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.create_date
     *
     * @param createDate the value for t_products_temp.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.status
     *
     * @return the value of t_products_temp.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.status
     *
     * @param status the value for t_products_temp.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.execute_date
     *
     * @return the value of t_products_temp.execute_date
     *
     * @mbggenerated
     */
    public Date getExecuteDate() {
        return executeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.execute_date
     *
     * @param executeDate the value for t_products_temp.execute_date
     *
     * @mbggenerated
     */
    public void setExecuteDate(Date executeDate) {
        this.executeDate = executeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_products_temp.logistics
     *
     * @return the value of t_products_temp.logistics
     *
     * @mbggenerated
     */
    public String getLogistics() {
        return logistics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_products_temp.logistics
     *
     * @param logistics the value for t_products_temp.logistics
     *
     * @mbggenerated
     */
    public void setLogistics(String logistics) {
        this.logistics = logistics == null ? null : logistics.trim();
    }
}