package com.buyauto.mapper.user;

import org.apache.ibatis.annotations.Param;

import com.buyauto.entity.user.TUsersSales;

public interface TUsersSalesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users_sales
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users_sales
     *
     * @mbggenerated
     */
    int insert(TUsersSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users_sales
     *
     * @mbggenerated
     */
    int insertSelective(TUsersSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users_sales
     *
     * @mbggenerated
     */
    TUsersSales selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users_sales
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TUsersSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users_sales
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TUsersSales record);

	/** 
	* @Title: selectByUid 
	* @Description: 根据uid查询
	* @param @param uid
	* @param @return    设定文件 
	* @return TUsersSales    返回类型 
	* @throws 
	*/
	TUsersSales selectByUid(@Param("uId")Long uId);
	/**
	 * 根据对应ID查询个人审核原因
	 * @return
	 */
	String getNotPassInfoByMId(@Param("id")Long mid);
	/**
	 * 修改状态
	 * @param id
	 * @param result 1通过 2不通过
	 * @return
	 */
	int updateStatusByUid(@Param("uId")Long id, @Param("result")Integer result);

}