package com.buyauto.mapper.user;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.buyauto.entity.user.TUsersMsg;

public interface TUsersMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users_msg
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users_msg
     *
     * @mbggenerated
     */
    int insert(TUsersMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users_msg
     *
     * @mbggenerated
     */
    int insertSelective(TUsersMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users_msg
     *
     * @mbggenerated
     */
    TUsersMsg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users_msg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TUsersMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users_msg
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TUsersMsg record);

    /**
	 * 分页条件查询信息中心列表
     * @param id 
	 * @param page 页码
	 * @param rows 一页条数
	 */
	List<TUsersMsg> queryMessage(@Param("id")Long id, @Param("startNumber") int page,@Param("endNumber") int rows);

	/**
     * 查找总条数
     */
	int queryMessageCount(@Param("id")Long id);

	void updateAllReadByUid(@Param("uId")Long uId);


}