package com.buyauto.mapper.user;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.buyauto.dao.orders.TUsersCommissionDao;
import com.buyauto.dao.user.TUsersRecommenderDao;
import com.buyauto.entity.user.TUsersRecommender;

public interface TUsersRecommenderMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_users_recommender
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_users_recommender
	 *
	 * @mbggenerated
	 */
	int insert(TUsersRecommender record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_users_recommender
	 *
	 * @mbggenerated
	 */
	int insertSelective(TUsersRecommender record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_users_recommender
	 *
	 * @mbggenerated
	 */
	TUsersRecommender selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_users_recommender
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(TUsersRecommender record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_users_recommender
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(TUsersRecommender record);

	TUsersRecommender selectRecommenderByPhone(@Param("name") String name, @Param("phone") String recommender);

	List<TUsersRecommenderDao> selectRecommenderByUid(@Param("pageStartNumber") int pageStartNumber,
			@Param("pageEndNumber") int pageEndNumber, @Param("uId") String uId, @Param("type") Integer type,
			@Param("fatherId") String father, @Param("grandpaId") String grandfather,
			@Param("startTime") Date strStartDates, @Param("endTime") Date strEndDates);

	int selectCountRecommenderByUid(@Param("uId") String uId, @Param("type") Integer type,
			@Param("fatherId") String father, @Param("grandpaId") String grandfather,
			@Param("startTime") Date strStartDates, @Param("endTime") Date strEndDates);

	TUsersRecommender getRecommenderByUid(@Param("uId") Long uId);

}